language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt --allow-all-external --use-mirrors"
# command to run tests
script: DJANGO_SETTINGS_MODULE="gettingstarted.settings" nosetests

